# Generated by Django 5.2.3 on 2025-06-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipogasto_remove_doctor_duracion_cita_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposangre',
            options={'ordering': ['tipo'], 'verbose_name': 'Tipo de Sangre', 'verbose_name_plural': 'Tipos de Sangre'},
        ),
        migrations.AlterField(
            model_name='tiposangre',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion'),
        ),
    ]
