# Generated by Django 5.2.1 on 2025-06-29 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tiposangre_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto_referencia',
            field=models.ForeignKey(blank=True, help_text='Referencia a una foto del módulo Fotos de Pacientes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_que_usan_foto', to='core.fotopaciente', verbose_name='Foto de Referencia'),
        ),
    ]
