# Generated by Django 5.2.1 on 2025-07-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_atencion_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citamedica',
            name='paciente',
        ),
        migrations.AddField(
            model_name='citamedica',
            name='apellido_paciente',
            field=models.CharField(default='Desconocido', max_length=100, verbose_name='Apellido del Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citamedica',
            name='cedula_paciente',
            field=models.CharField(default='Sin dato', max_length=20, verbose_name='Cédula del Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citamedica',
            name='direccion_paciente',
            field=models.CharField(default='Sin dato', max_length=255, verbose_name='Dirección del Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citamedica',
            name='nombre_paciente',
            field=models.CharField(default='Sin dato', max_length=100, verbose_name='Nombre del Paciente'),
            preserve_default=False,
        ),
    ]
